### ISSUE TITLE
地図をリメイクする

### ISSUE THREAD

**Issue by almandite1** [almandite1/shogunate_map_alteration#141]
あたらしい DEM を使用して地図を作り替えることができるか検証してみる。

## current
- 15 arcseconds（＝15×30meter=450m/pixel）
- 8bit Grayscale（256階調）

## plan
- 1 arcseconds（＝1×30meter=30m/pixel）→ 120m/pixel
- 16bit Grayscale（int16, -32,768 ～ 32,767）

## road map
- [x] DEM をダウンロードする
  - [x] 北緯45度以北
  - [x]  北緯40度以北
  - [x] 北緯35度以北
  - [x] 北緯30度以北
  - [x] 北緯25度以北
  - [x] 北緯20度以北
  - [x] 北緯15度以北
- [x] マージする
  - [x] 北緯45度以北
  - [x]  北緯40度以北
  - [x] 北緯35度以北
  - [x] 北緯30度以北
  - [x] 北緯25度以北
  - [x] 北緯20度以北
  - [x] 北緯15度以北
- [x] 解像度を落とす　30m/pixel→ 120m/pixel, 240m/pixel
  - [x] 北緯45度以北
  - [x]  北緯40度以北
  - [x] 北緯35度以北
  - [x] 北緯30度以北
  - [x] 北緯25度以北
  - [x] 北緯20度以北
  - [x] 北緯15度以北
- [x] 1つにマージする
- [x] 再投影
- [x] 横幅が足りないので再ダウンロード
  - [x] N22E105-N22E113
  - [x] N21E105-N21E113
  - [x] N20E105-N20E113
- [x] N20-N29 を再びマージ
- [x] N20-N29 をまた解像度落とし
- [x] 再び1つにマージする
- [x] 北緯64度を追加する
- [x] Provinces.png をエクスポートする　18432×18432→16256×10378 13964×13964→12288×8192？
- [x] また再投影＆ Provinces.png で切り抜き
- [x] heightmap.png をエクスポートする
- [x] 位置を合わせ、変形させ、切り抜き
- [x] map editor で heightmap.png を読み込めるかテストする（現行16,384×4096＝6710万8864。20,480×20,480＝419,430,400ピクセル:ok:）
- [x] map editor で repack が動作するかテストする（18,432×18,432＝3億39,73万8,624:ng:　12,000×12,000＝1億14,00万0,000は:ok:との報告あり、目標は 12288×8192＝1億00,66万3,296）
- [x] map editor  で 12288×8192＝1億00,66万3,296 repack 成功　
 
高さ 9,216 では常時 terrain エラーが出る。

- [x] 他のファイルの画像サイズを変更
- [x] おおまかなマップロケーターを生成と調整
- [x] heightmap の湖を調整
- [x] lake object を湖に配置
- [x] 地面のテクスチャを生成
- [x] surround_map を作り直す。https://imperator.paradoxwikis.com/Map_modding

|ファイル名|heightmapサイズ比|目的サイズ|色の要素（内→外）|役割|mipmap有無|DDS|
|-|-|-|-|-|-|-|
|surround_fade.dds|1/8| 1536*1024 | 黄色→赤色→黒 | 紙地図の、木の上の紙の範囲 | なし | DXT1 |
|surround_mask.dds|1/2| 6144*4096 | 黒→黄色、青色 | 雲の範囲 | あり | DXT1 |

- [x] colormap.dds を作り直す 1/4 非圧縮　3072*2048
- [x] flatmap.dds を作り直す
- [x] flowmap.dds を作り直す 1/4 8bit RGB DXT5
- [x] foam_map.dds 1/8　DXT5 mipmap 8bit RGB 
- [x] watercolor_rgb_waterspec_a.dds 1/2 非圧縮

**Comment by almandite1** [comment]
16bit grayscale heightmap トーンカーブ

|入力|出力|結果|
|-|-|-|
|0|3|低い|
|10|7.5||
|30|20||
|100|60||

**Comment by almandite1** [comment]
選択範囲の情報

12288px
8192px

左上の座標
4834
5659
